CREATE TABLE IF NOT EXISTS `coviddeaths` (
    `iso_code` VARCHAR(3) CHARACTER SET utf8mb4,
    `continent` VARCHAR(20) CHARACTER SET utf8mb4,
    `location` VARCHAR(30) CHARACTER SET utf8mb4,
    `date` DATETIME,
    `total_cases` NUMERIC(20, 1),
    `new_cases` NUMERIC(20, 1),
    `new_cases_smoothed` NUMERIC(6, 3),
    `total_deaths` NUMERIC(20, 1),
    `new_deaths` NUMERIC(20, 1),
    `new_deaths_smoothed` NUMERIC(4, 3),
    `total_cases_per_million` NUMERIC(5, 3),
    `new_cases_per_million` NUMERIC(5, 3),
    `new_cases_smoothed_per_million` NUMERIC(4, 3),
    `total_deaths_per_million` NUMERIC(4, 3),
    `new_deaths_per_million` NUMERIC(4, 3),
    `new_deaths_smoothed_per_million` NUMERIC(4, 3),
    `reproduction_rate` NUMERIC(3, 2),
    `icu_patients` INT,
    `icu_patients_per_million` INT,
    `hosp_patients` INT,
    `hosp_patients_per_million` INT,
    `weekly_icu_admissions` INT,
    `weekly_icu_admissions_per_million` INT,
    `weekly_hosp_admissions` INT,
    `weekly_hosp_admissions_per_million` INT,
    `total_tests` INT,
    `new_tests` INT,
    `total_tests_per_thousand` INT,
    `new_tests_per_thousand` INT,
    `new_tests_smoothed` INT,
    `new_tests_smoothed_per_thousand` INT,
    `positive_rate` INT,
    `tests_per_case` INT,
    `tests_units` INT,
    `total_vaccinations` INT,
    `people_vaccinated` INT,
    `people_fully_vaccinated` INT,
    `total_boosters` INT,
    `new_vaccinations` INT,
    `new_vaccinations_smoothed` INT,
    `total_vaccinations_per_hundred` INT,
    `people_vaccinated_per_hundred` INT,
    `people_fully_vaccinated_per_hundred` INT,
    `total_boosters_per_hundred` INT,
    `new_vaccinations_smoothed_per_million` INT,
    `new_people_vaccinated_smoothed` INT,
    `new_people_vaccinated_smoothed_per_hundred` INT,
    `stringency_index` NUMERIC(4, 2),
    `population_density` NUMERIC(5, 3),
    `median_age` NUMERIC(3, 1),
    `aged_65_older` NUMERIC(4, 3),
    `aged_70_older` NUMERIC(4, 3),
    `gdp_per_capita` NUMERIC(7, 3),
    `extreme_poverty` INT,
    `cardiovasc_death_rate` NUMERIC(6, 3),
    `diabetes_prevalence` NUMERIC(3, 2),
    `female_smokers` INT,
    `male_smokers` INT,
    `handwashing_facilities` NUMERIC(5, 3),
    `hospital_beds_per_thousand` NUMERIC(2, 1),
    `life_expectancy` NUMERIC(4, 2),
    `human_development_index` NUMERIC(4, 3),
    `population` NUMERIC(20, 1),
    `excess_mortality_cumulative_absolute` INT,
    `excess_mortality_cumulative` INT,
    `excess_mortality` INT,
    `excess_mortality_cumulative_per_million` INT
);